sudo: required
language: cpp
compiler: gcc
script: travis/script.sh

before_install:
    # Travis CI's mac os environment doesn't set java home properly. This is
    # done here and not in the before_install.sh script since exporting the
    # variable in a called script won't update the caller environment scope.
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=$(/usr/libexec/java_home) ; fi
    - travis/before_install.sh

after_success:
    - bash <(curl -s https://codecov.io/bash)

os:
    - osx
    - linux

env:
    matrix:
        - DISTRO=none # need a row in the build matrix for osx
        - DISTRO=ubuntu VER=14.04
        - DISTRO=centos VER=6

matrix:
    exclude:
        - os: osx
          env: DISTRO=ubuntu VER=14.04
        - os: osx
          env: DISTRO=centos VER=6
        - os: linux
          env: DISTRO=none

services:
    - docker

before_deploy:
    - mkdir artifacts
    - sudo mv build/*.tgz artifacts # docker uses root when writing tarball

deploy:
    provider: s3
    bucket: quantcast-qfs
    skip_cleanup: true
    region: us-east-1
    local_dir: artifacts
    access_key_id:
        - secure: IvmQ1sHBE+/USw+/adukFk1Wxq9Pn49PTvlbbRoI1D3W+ILc7u7+rFuNwQqAexXfBP71oMEE8YDR4U9dcoD4NinMd02lciFzrbtzErQ2Re2fU6k3I2OiyJ8ApAalKLxNmFC8jPTPufFT8gfCfOjoSDIpEffA75EzJVmDdDOspvw=
    secret_access_key:
        - secure: HkCLJKSX7jUPzsbZeiK3pSwECP79q6ypRnzudsTlRzmbW/eKloJHLwPEZycAakH9S24cqgjKTvv1O8XZ8sTGx0lhonRRBOXeYN9tVKrwL7CIbDHy4fOJkVQYG321EmKr3UIL9rAYZyR01WC1hEJ6pPJK7xgcFTDhZ0e47wegUlI=
